<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net9.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>Latest</LangVersion>
		<Nullable>enable</Nullable>
		<IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">true</IsAotCompatible>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<Authors>ds5678</Authors>
		<Company>AssetRipper</Company>
		<Version>1.5.0</Version>
		<AssemblyVersion>$(Version)</AssemblyVersion>
		<PackageId>AssetRipper.Mining.PredefinedAssets</PackageId>
		<PackageTags>C# Unity</PackageTags>
		<RepositoryUrl>https://github.com/AssetRipper/AssetRipper.Mining</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryType>git</RepositoryType>
		<PackageProjectUrl>$(RepositoryUrl)</PackageProjectUrl>
		<Copyright>Copyright (c) 2023 - 2025 ds5678</Copyright>
		<Description>Library for storing datamined asset information.</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>

		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AssetRipper.Primitives" Version="3.1.6" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="PolySharp" Version="1.15.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="System.Text.Json" Version="9.0.4" />
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
